//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hackteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Roles
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public string role { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
