//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hackteam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Roles
    {
        public int id { get; set; }
        public string role { get; set; }
        public int user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
